### ISSUE TITLE
span and class

### ISSUE THREAD

**Issue by mikebutts** [philrubin/prj-rev-bwfs-dasmoto#1]
https://github.com/philrubin/prj-rev-bwfs-dasmoto/blob/d023b409fd4e7ded491d47f2ed05d42c65923428/Dasmotos/index.html#L31

Great job with proper use of spans with classes, it is rare that people get this on the first project.

**Comment by philrubin** [comment]
I already went through the lessons on Codeacademy.  I'm doing this to put what i learned to work.
