### ISSUE TITLE
Folder caps

### ISSUE THREAD

**Issue by mikebutts** [philrubin/prj-rev-bwfs-dasmoto#2]
https://github.com/philrubin/prj-rev-bwfs-dasmoto/blob/d023b409fd4e7ded491d47f2ed05d42c65923428/Dasmotos/index.html#L4

Be careful when naming folders, they should always match.
![image](https://user-images.githubusercontent.com/8017734/34484743-ed41b3b4-ef94-11e7-92fd-f5c76549d6c1.png)

I always use lowercase to make sure I don't run into issues.

**Comment by philrubin** [comment]
ok
